In [7]:
import numpy as np

matriz = np.arange(18).reshape(3, 6)
print(matriz)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [8]:
# shape -> Nos brinda cuantas filas y columnas respectivamente tiene una matriz (3, 6)
print(matriz.shape)

(3, 6)


In [9]:
# ndim -> Para ver el número de dimensiones de nuestra matriz en este caso 2 -> 2 Dimensiones
print(matriz.ndim)

2


In [10]:
# size -> Para identificar el total de elementos de la matriz o array
print(matriz.size)

18


In [12]:
# zeros() -> Para generar matriz de ceros 
matrizc = np.zeros((3, 4))
print(matrizc)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Matrices de 3D

In [13]:
matriz = np.arange(27).reshape(3, 3, 3)
print(matriz)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
