## Listas vs Arrays

Listas: Puede constar de elementos pertenecientes a distintos tipos de datos.

Arrays: Solo consta de elementos que pertenecen al mismo tipo de datos.

In [3]:
import array as arr

matriz = arr.array('i', [1, 2, 3, 42, 43, 51]) # 'i' es el identificador de integer

for arr in matriz:
    print(arr)

1
2
3
42
43
51


In [5]:
import numpy as np

matriz = np.array([1, 2, 3, 42, 43, 51])
print(matriz)

[ 1  2  3 42 43 51]


In [ ]:
import numpy as np

lista = [1, 3, 5]
matriz = np.array([2, 4, 6])

print(lista) # Colección de datos
print(matriz) # Cada uno de sus elementos son independientes ya que ocupan diferentes espacios de memoria

[1, 3, 5]
[2 4 6]


In [7]:
lista.append(7)
matriz.append(8)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [8]:
matriz = matriz + np.array([8])

In [ ]:
print(lista)
print(matriz)

[1, 3, 5, 7]
[10 12 14]


Listas: No pueden manejar operaciones aritmeticas directamente.

Arrays: Puede manejar directamente operaciones aritmeticas.

In [10]:
# Aplicando operaciones aritmeticas a listas

lista1 = [1, 2, 3]
lista2 = [4, 5, 6]

# Suma: No se suman se concatenan
print(lista1 + lista2)
# Multiplicación: Da error
print(lista1 * lista2)

[1, 2, 3, 4, 5, 6]


TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
# Aplicando operaciones aritmeticas a arrays o matrices

matriz1 = np.array([1, 2, 3])
matriz2 = np.array([4, 5, 6])

# Suma: Suma cada uno de los valores del primer array con los valores del segundo: es decir, 1 + 4, 2 + 5 y 3 + 6
print(matriz1 + matriz2)

# Multiplicación: Hace casi lo mismo con la diferencia de que multiplica