In [ ]:
import numpy as np

# Array 1D: Una dimensión
matriz = np.array([1, 2, 3, 4, 5, 6, 7])
print(matriz)


[1 2 3 4 5 6 7]


In [3]:
matriz2d = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz2d) # Matriz o array 2D de 2 x 3

[[1 2 3]
 [4 5 6]]


In [4]:
lista = [1, 2, 3, 4, 5]
matriz = np.array(lista) # Le pasamos una lista como argumento para generar un array
print(matriz)

[1 2 3 4 5]


In [5]:
lista = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matriz3d = np.array(lista) # Le estamos pasando una lista para generar un array 3D
print(matriz3d) # Array o matriz 3D de 3 x 3

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Crear matrices mediante rangos:

matriz = np.arange(12).reshape(3, 4) # reshape() se usa para generar la estructura ya sea 3 x 3 o en este caso 3 x 4 tiene que cumplir al multiplicar 3 x 4 = 12
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
